### ISSUE TITLE
spotipy-random should probably be spotipy_random

### ISSUE THREAD

**Issue by Madbrad200** [michimalek/spotipy-random#1]
`from spotipy-random import get_random`

```
flake8: error
E999 - SyntaxError: invalid syntax
```

importing `spotipy-random` produces a syntax error (caused by the dash). Some [brief research suggests dashes](https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them) should not be used in module names for a number of reasons.

It seems like a workaround atm is to use `import_module`:

```
from importlib import import_module
python_code = import_module('spotipy-random')
```

However this is a bit annoying to have to do. Might be better to rename it to spotipy_random to avoid syntax issues?

**Comment by EuleMitKeule** [comment]
Thank you for your issue! 

You are right, imports with dashes don't work, but the module can already be imported with `import spotipy_random`. 
However this was just done wrongly in the example code in the Readme.
I fixed this in ff14bdf.
