### ISSUE TITLE
Where are songs saved to?

### ISSUE THREAD

**Issue by valentinback** [michimalek/spotipy-random#2]
Code and API communication run fine, however, I am unsure as to where the randomly selected song is being saved to? Is it being saved locally or added to a Spotify playlist (this would be preferred). Any help would be appreciated, thanks! :)

**Comment by EuleMitKeule** [comment]
@valentinback The `get_random` method can only be used to get a random song from the Spotify API. The resulting song response is returned in JSON format. No interaction with your user account takes place.
