### ISSUE TITLE
random_pop_song_json... line stopped responding

### ISSUE THREAD

**Issue by valentinback** [michimalek/spotipy-random#3]
Ran into an issue today as the code suddenly stopped responding / executing while executing the following line (execution through a for loop was completely fine beforehand without changing anything):
random_pop_song_json : str = get_random(spotify=spotify_client, type="track", genre=genre_type, year="2002-2021")

Tried with a completely separate client ID etc. but execution keeps lagging in this line so I would assume that this isn't related to the Spotify API limits or similar... Has anything changed in the library or is there another obvious reason that would explain this issue?

Thanks already in advance :)

**Comment by michimalek** [comment]
Sorry for replying so late, I hope you have already found a solution for this problem because so far we have changed nothing in the code. We are using the random spotipy extension for our personal project as well and there it still returns random songs as it should be.
